name: service
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mongo_dart: any
  rpc: ^0.6.2
  global:
    path: ..
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
